import { Template } from "@/types";

export const TEMPLATES: Template[] = [
  // 科技行业
  {
    id: "modern-blue",
    name: "Modern Blue",
    category: "Technology",
    industry: "科技",
    style: "简约",
    colorScheme: "blue",
    free: true,
    preview: "Modern and clean design with blue accents",
    description: "Perfect for tech roles - clean layout, ATS-friendly, professional look",
  },
  {
    id: "tech-orange",
    name: "Tech Orange",
    category: "Technology",
    industry: "科技",
    style: "现代",
    colorScheme: "orange",
    free: false,
    preview: "Bold tech-focused design",
    description: "Stand out with this modern template for developers and engineers",
  },
  {
    id: "tech-dark",
    name: "Dark Tech",
    category: "Technology",
    industry: "科技",
    style: "创意",
    colorScheme: "slate",
    free: true,
    preview: "Sleek dark theme design",
    description: "Perfect for software engineers and tech professionals",
  },
  {
    id: "tech-minimal",
    name: "Minimal Tech",
    category: "Technology",
    industry: "科技",
    style: "简约",
    colorScheme: "emerald",
    free: true,
    preview: "Ultra-clean minimalist design",
    description: "Ideal for senior developers and tech leads",
  },
  // 金融行业
  {
    id: "finance-classic",
    name: "Classic Finance",
    category: "Finance",
    industry: "金融",
    style: "经典",
    colorScheme: "slate",
    free: true,
    preview: "Traditional finance design",
    description: "Perfect for bankers, analysts, and finance professionals",
  },
  {
    id: "finance-blue",
    name: "Professional Finance",
    category: "Finance",
    industry: "金融",
    style: "简约",
    colorScheme: "blue",
    free: true,
    preview: "Clean professional design",
    description: "Ideal for investment banking and corporate finance roles",
  },
  {
    id: "finance-modern",
    name: "Modern Finance",
    category: "Finance",
    industry: "金融",
    style: "现代",
    colorScheme: "teal",
    free: false,
    preview: "Modern financial design",
    description: "Great for fintech and modern finance positions",
  },
  {
    id: "finance-traditional",
    name: "Traditional Banking",
    category: "Finance",
    industry: "金融",
    style: "传统",
    colorScheme: "orange",
    free: true,
    preview: "Conservative banking design",
    description: "Perfect for traditional banking roles",
  },
  // 创意行业
  {
    id: "creative-teal",
    name: "Creative Teal",
    category: "Creative",
    industry: "创意",
    style: "创意",
    colorScheme: "teal",
    free: true,
    preview: "Modern creative design with teal accents",
    description: "Great for designers, marketers, and creative professionals",
  },
  {
    id: "creative-colorful",
    name: "Colorful Creative",
    category: "Creative",
    industry: "创意",
    style: "创意",
    colorScheme: "orange",
    free: false,
    preview: "Vibrant colorful design",
    description: "Perfect for artists, designers, and creative directors",
  },
  {
    id: "creative-minimal",
    name: "Minimal Creative",
    category: "Creative",
    industry: "创意",
    style: "简约",
    colorScheme: "slate",
    free: true,
    preview: "Clean minimalist creative design",
    description: "Ideal for UX designers and digital artists",
  },
  {
    id: "creative-modern",
    name: "Modern Creative",
    category: "Creative",
    industry: "创意",
    style: "现代",
    colorScheme: "blue",
    free: true,
    preview: "Contemporary creative design",
    description: "Great for marketing professionals and content creators",
  },
  // 学术行业
  {
    id: "academic-emerald",
    name: "Academic Emerald",
    category: "Academic",
    industry: "学术",
    style: "经典",
    colorScheme: "emerald",
    free: false,
    preview: "Formal academic design",
    description: "Perfect for PhDs, researchers, and academic positions",
  },
  {
    id: "academic-simple",
    name: "极简学术简历",
    category: "Academic",
    industry: "学术",
    style: "简约",
    colorScheme: "slate",
    free: true,
    preview: "Clean academic design",
    description: "清爽无装饰，突出教育背景、论文发表与研究项目",
  },
  {
    id: "academic-modern",
    name: "分栏式学术简历",
    category: "Academic",
    industry: "学术",
    style: "现代",
    colorScheme: "blue",
    free: true,
    preview: "Two-column academic design",
    description: "左右分栏布局，左侧放个人信息，右侧放成果与经历",
  },
  {
    id: "academic-classic",
    name: "传统学术CV",
    category: "Academic",
    industry: "学术",
    style: "经典",
    colorScheme: "emerald",
    free: true,
    preview: "Traditional academic CV",
    description: "符合国际学术CV规范，侧重发表论文、会议报告与学术荣誉",
  },
  // 专业商务
  {
    id: "professional-gray",
    name: "Professional Gray",
    category: "Business",
    industry: "商务",
    style: "传统",
    colorScheme: "slate",
    free: true,
    preview: "Timeless professional design with gray tones",
    description: "Ideal for finance, consulting, and corporate roles",
  },
  {
    id: "business-blue",
    name: "Corporate Blue",
    category: "Business",
    industry: "商务",
    style: "简约",
    colorScheme: "blue",
    free: true,
    preview: "Corporate professional design",
    description: "Perfect for managers and executives",
  },
  {
    id: "business-modern",
    name: "Modern Business",
    category: "Business",
    industry: "商务",
    style: "现代",
    colorScheme: "teal",
    free: false,
    preview: "Modern corporate design",
    description: "Great for consultants and business analysts",
  },
];

export const INDUSTRIES = [
  "Technology",
  "Finance",
  "Creative",
  "Academic",
  "Healthcare",
  "Marketing",
  "Consulting",
  "Sales",
];

export const ATS_KEYWORDS_BY_ROLE = {
  "Software Developer": [
    "JavaScript",
    "Python",
    "React",
    "Node.js",
    "Git",
    "Agile",
    "API",
    "REST",
    "SQL",
    "TypeScript",
    "Debugging",
    "Unit Testing",
    "CI/CD",
    "Docker",
    "AWS",
  ],
  "Product Manager": [
    "Agile",
    "Scrum",
    "User Stories",
    "Jira",
    "Roadmapping",
    "MVP",
    "Data Analysis",
    "Strategic Planning",
    "Product Lifecycle",
    "User Experience",
    "Stakeholder Management",
    "KPI Tracking",
  ],
  "Data Analyst": [
    "SQL",
    "Excel",
    "Tableau",
    "Power BI",
    "Python",
    "R",
    "Data Visualization",
    "Statistical Analysis",
    "Data Cleaning",
    "Reporting",
    "Dashboard",
    "ETL",
  ],
  "UI/UX Designer": [
    "Figma",
    "Sketch",
    "Wireframing",
    "Prototyping",
    "User Research",
    "Usability Testing",
    "Design Systems",
    "Visual Design",
    "Interaction Design",
    "Adobe XD",
  ],
};

export const SAMPLE_EXPERIENCE = [
  "Developed and maintained web applications using React and Node.js",
  "Collaborated with cross-functional teams to define, design, and ship new features",
  "Improved application performance by 40% through code optimization",
  "Mentored junior developers and conducted code reviews",
];

export const RESUME_TIPS = [
  "Use active verbs like 'Developed', 'Led', 'Created', 'Implemented'",
  "Quantify your achievements with numbers (e.g., 'Increased sales by 20%')",
  "Keep your resume to 1-2 pages maximum",
  "Use plain text, avoid complex tables and graphics for ATS compatibility",
  "Tailor your resume for each job application",
  "Include relevant keywords from the job description",
];
