import { Template } from "@/types";

export const TEMPLATES: Template[] = [
  {
    id: "modern-blue",
    name: "Modern Blue",
    category: "Technology",
    style: "Minimal",
    colorScheme: "blue",
    free: true,
    preview: "Modern and clean design with blue accents",
    description: "Perfect for tech roles - clean layout, ATS-friendly, professional look",
  },
  {
    id: "professional-gray",
    name: "Professional Gray",
    category: "Business",
    style: "Traditional",
    colorScheme: "slate",
    free: true,
    preview: "Timeless professional design with gray tones",
    description: "Ideal for finance, consulting, and corporate roles",
  },
  {
    id: "creative-teal",
    name: "Creative Teal",
    category: "Creative",
    style: "Creative",
    colorScheme: "teal",
    free: true,
    preview: "Modern creative design with teal accents",
    description: "Great for designers, marketers, and creative professionals",
  },
  {
    id: "academic-emerald",
    name: "Academic Emerald",
    category: "Academic",
    style: "Classic",
    colorScheme: "emerald",
    free: false,
    preview: "Formal academic design",
    description: "Perfect for PhDs, researchers, and academic positions",
  },
  {
    id: "tech-orange",
    name: "Tech Orange",
    category: "Technology",
    style: "Modern",
    colorScheme: "orange",
    free: false,
    preview: "Bold tech-focused design",
    description: "Stand out with this modern template for developers and engineers",
  },
];

export const INDUSTRIES = [
  "Technology",
  "Finance",
  "Creative",
  "Academic",
  "Healthcare",
  "Marketing",
  "Consulting",
  "Sales",
];

export const ATS_KEYWORDS_BY_ROLE = {
  "Software Developer": [
    "JavaScript",
    "Python",
    "React",
    "Node.js",
    "Git",
    "Agile",
    "API",
    "REST",
    "SQL",
    "TypeScript",
    "Debugging",
    "Unit Testing",
    "CI/CD",
    "Docker",
    "AWS",
  ],
  "Product Manager": [
    "Agile",
    "Scrum",
    "User Stories",
    "Jira",
    "Roadmapping",
    "MVP",
    "Data Analysis",
    "Strategic Planning",
    "Product Lifecycle",
    "User Experience",
    "Stakeholder Management",
    "KPI Tracking",
  ],
  "Data Analyst": [
    "SQL",
    "Excel",
    "Tableau",
    "Power BI",
    "Python",
    "R",
    "Data Visualization",
    "Statistical Analysis",
    "Data Cleaning",
    "Reporting",
    "Dashboard",
    "ETL",
  ],
  "UI/UX Designer": [
    "Figma",
    "Sketch",
    "Wireframing",
    "Prototyping",
    "User Research",
    "Usability Testing",
    "Design Systems",
    "Visual Design",
    "Interaction Design",
    "Adobe XD",
  ],
};

export const SAMPLE_EXPERIENCE = [
  "Developed and maintained web applications using React and Node.js",
  "Collaborated with cross-functional teams to define, design, and ship new features",
  "Improved application performance by 40% through code optimization",
  "Mentored junior developers and conducted code reviews",
];

export const RESUME_TIPS = [
  "Use active verbs like 'Developed', 'Led', 'Created', 'Implemented'",
  "Quantify your achievements with numbers (e.g., 'Increased sales by 20%')",
  "Keep your resume to 1-2 pages maximum",
  "Use plain text, avoid complex tables and graphics for ATS compatibility",
  "Tailor your resume for each job application",
  "Include relevant keywords from the job description",
];
